### ISSUE TITLE
Feature discussion

### ISSUE THREAD

**Issue by hanksudo** [kidark/wtd#4]
## TODOs

- [ ] `wtd github_repo_url` show used packages on project
- [ ] `wtd npm express` show [express](https://github.com/expressjs/express) dependencies
- [ ] Chrome extension to show dependencies on Github
- [ ] Web API based on NodeJS
- [ ] Alfred called WTD API by Python

**Comment by hanksudo** [comment]
@amowu Now execute `wtd npm wtd -u` look like this:

```
babel-polyfill -  - https://github.com/babel/babel/tree/master/packages/babel-polyfill
meow - CLI app helper - git+https://github.com/sindresorhus/meow.git
node-fetch - A light-weight module that brings window.fetch to node.js and io.js - git+https://github.com/bitinn/node-fetch.git
```

how about become this?

```markdown
- [babel-polyfill](https://github.com/babel/babel/tree/master/packages/babel-polyfill)

- [meow](https://github.com/sindresorhus/meow)
CLI app helper

- [node-fetch](https://github.com/bitinn/node-fetch)
A light-weight module that brings window.fetch to node.js and io.js
```

BTW, `git+https://github.com/bitinn/node-fetch.git` should be `https://github.com/bitinn/node-fetch` or homepage url.

Maybe we can provide a alternative `--format '{name} - {description} - {url}'` to custom format later.

**Comment by amowu** [comment]
@hanksudo terminal can support markdown format @@?

**Comment by hanksudo** [comment]
@amowu Can not.

But you can redirect `wtd npm wtd --format 'xxx' > dependencies.md`

I think this version we can leave it to:

```
name - description
url
```

or 

```
name - url
description
```

something like that.

**Comment by amowu** [comment]
@hanksudo how about this?

```
accepts                     https://github.com/jshttp/accepts.git
                                  Higher-level content negotiation
array-flatten             git://github.com/blakeembrey/array-flatten.git
                                  Flatten an array of nested arrays into a single flat array
content-disposition https://github.com/jshttp/content-disposition
                                  Create and parse Content-Disposition header
```

maybe we can use [text-table](https://github.com/substack/text-table) and [chalk](https://github.com/chalk/chalk)

**Comment by hanksudo** [comment]
@amowu sure, let's do that.

**Comment by hanksudo** [comment]
@amowu handle beauty terminal display first.

I think we can handle `--output` later.

**Comment by amowu** [comment]
@hanksudo when I survey `npm-check` packages use `wtd`, I find this [package-json](https://github.com/sindresorhus/package-json)

**Comment by amowu** [comment]
add WTD REST APIs feature
